### PR TITLE
added essential notebooks

### PR DESCRIPTION
**Pull request by Dhruv-VINT**
I have added a few notebooks which are an integral part for building core concepts for Data Science.
Also please add the hacktoberfest label here too !

### CODE REVIEW

**Comment by JoelBuenrostro** [comment]
Cool, now is labeled, thanks for the contribution.

**Comment by Dhruv-VINT** [comment]
It's still not showing up on my log, can you help me on this?

**Comment by Dhruv-VINT** [comment]
Hey @JoelBuenrostro sorry to disturb you again, but on the site it says, once the PR is merged the project maintainer has to assign the "hacktoberfest-accepted" label to it.

**Comment by JoelBuenrostro** [comment]
Oh. ok no problem

**Pull request merged**
